export const figurative_constants = [
  "*BLANKS",
  "*BLANK",
  "*ZEROS",
  "*ZERO",
  "*HIVAL",
  "*LOVAL",
  "*NULL",
  "*ON",
  "*OFF",
  "*ALL",
] as const;

export const file_operations = [
  "*INPUT",
  "*OUTPUT",
  "*UPDATE",
  "*DELETE",
  "*KEY",
  "*START",
  "*END",
  "*NEXT",
  "*PREV",
  "*FIRST",
  "*LAST",
  "*CANCL",
  "*DETL",
  "*GET",
] as const;
const control_options = [
  "*YES",
  "*NO",
  "*CALLER",
  "*NEW",
  "*INHERIT",
  "*SRCSTMT",
  "*NODEBUGIO",
  "*NOSRCSTMT",
  "*STDSQL",
  "*SYS",
  "*JOB",
  "*DATE",
  "*TIME",
  "*ISO",
  "*USA",
  "*EUR",
  "*JIS",
  "*MDY",
  "*DMY",
  "*YMD",
] as const;
const parameter_passing = [
  "*NOPASS",
  "*OMIT",
  "*VARSIZE",
  "*STRING",
  "*RIGHTADJ",
  "*CONVERT",
] as const;
const indicators = [
  "*INLR",
  "*INU1",
  "*INU2",
  "*INU3",
  "*INU4",
  "*INU5",
  "*INU6",
  "*INU7",
  "*INU8",
  "*IN01",
  "*IN02", // ... hasta *IN99
  "*INKA",
  "*INKB",
  "*INKC",
  "*INKD",
  "*INKE",
  "*INKF",
  "*INKG",
  "*INKH", // Funciones F1-F24
  "*INKL",
  "*INKM",
  "*INKN",
  "*INKP",
  "*INKQ",
  "*INKR",
  "*INKS",
  "*INKT",
  "*INKU",
  "*INKV",
  "*INKW",
  "*INKX",
] as const;
const data_definition = [
  "*EXT",
  "*VAR",
  "*CTDATA",
  "*PSSR",
  "*ENTRY",
  "*LIKE",
  "*ALIGN",
  "*NEXT",
  "*QUALIFIED",
] as const;
const builtInFunctionsPrefix = "%";
const special_values = [
  "*DATE",
  "*DAY",
  "*MONTH",
  "*YEAR",
  "*SYS",
  "*LIBL",
  "*CURLIB",
] as const;

export const rpgle_declarations = [
  { tag: 'dcl-f',  description: 'Files (Archivos)' },
  { tag: 'dcl-s',  description: 'Standalone Variables (Variables sueltas)' },
  { tag: 'dcl-ds', description: 'Data Structures (Estructuras de datos)' },
  { tag: 'dcl-c',  description: 'Constants (Constantes)' },
  { tag: 'dcl-pr', description: 'Prototype (Prototipo para llamadas externas)' },
  { tag: 'dcl-pi', description: 'Procedure Interface (Parámetros recibidos)' },
  { tag: 'dcl-proc', description: 'Procedure (Inicio de procedimiento)' },
  { tag: 'dcl-enum', description: 'Enumeration (Lista de valores constantes)' }
] as const;

const rpgleDataTypes = [
  { type: 'PACKED',  rpgle: 'packed(len:dec)',  desc: 'Decimal empacado (Base de datos)' },
  { type: 'ZONED',   rpgle: 'zoned(len:dec)',   desc: 'Decimal zonado (Formato legible)' },
  { type: 'INT',     rpgle: 'int(3|5|10|20)',   desc: 'Entero con signo (Eficiente)' },
  { type: 'UNS',     rpgle: 'uns(3|5|10|20)',   desc: 'Entero sin signo' },
  { type: 'CHAR',    rpgle: 'char(len)',        desc: 'Cadena de longitud fija' },
  { type: 'VARCHAR', rpgle: 'varchar(len)',     desc: 'Cadena de longitud variable' },
  { type: 'IND',     rpgle: 'ind',              desc: 'Indicador booleano' },
  { type: 'DATE',    rpgle: 'date',             desc: 'Fecha (ISO, DMY, etc.)' },
  { type: 'TIMESTAMP', rpgle: 'timestamp',      desc: 'Fecha y hora con microsegundos' },
  { type: 'POINTER', rpgle: 'pointer',          desc: 'Dirección de memoria' }
] as const;